### ISSUE TITLE
Questions about Irony-Mode

### ISSUE THREAD

**Issue by joca-bt** [Sarcasm/irony-mode#172]
If I understood correctly, Irony-Mode provides C++ completion, syntax checking, and documentation support. However, how does it compare with the built-in support for C++ in Company and Flycheck?

Sorry for the questions, I am trying to understand the advantages of using Irony, which from the README are not clear.

**Comment by Sarcasm** [comment]
Oh, that's a perfectly valid question I guess :).

The way irony difference itself from `company-clang` and flycheck's clang and gcc checkers is that irony has background program running to handle the completion, a continuous **session**. This means that between 2 completions most of the parsing work is already in cache, offering better performance. company and flycheck use the clang binary, they launch it, it "compiles the code" and then forget about it. Then you it's launched again for the next completion but it doesn't benefit from the previous parsing.

The idea behind irony is also that it should provide support for compile options, so that all kind of IDE features are possible in the future. irony knows the compile options for the project so it can tailor Emacs to C++. It means you only have to configure irony for you project and you can have both completion and syntax checking for your file, if you want flycheck and company to have the proper flag you will have to specify it differently for both of them.

**Comment by Sarcasm** [comment]
Hope that was clear.

Closing.
