### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by akermu** [Sarcasm/irony-mode#199]
Hello,

is it possible to release a new version, as there are some nice features added since the last one?
Thanks a lot for your great package!

~akermu

**Comment by Sarcasm** [comment]
I will make a new release when it's ready. It's taking time I know but that's how it is. I try to make new release when the stuff inside is somewhat stable. Right now I plan on changing a lot things in the unreleased stuff. Once I'm ready I will make a new release but right now one shouldn't consider irony-mode "stable", that's why you won't see the master branch MELPA stable.
