### ISSUE TITLE
irony-mode doesn't recognize -include option

### ISSUE THREAD

**Issue by yuutayamada** [Sarcasm/irony-mode#201]
Hello, is it possible to use -include option?

I tried the way of .clang_complete file and this is my setting:

.clang_complete
```
-include /home/uta/share/devkit/arduino-1.6.3/hardware/arduino/avr/cores/arduino/Arduino.h
-I/home/uta/share/devkit/arduino-1.6.3/hardware/arduino/avr/cores/arduino/
-I/home/uta/share/devkit/arduino-1.6.3/hardware/tools/avr/include/
-I/home/uta/share/devkit/arduino-1.6.3/hardware/arduino/avr/libraries/
```

In my test code, I could use irony's auto-complete (M-x ac-complete-irony-async) if I add `#include <Arduino.h>`. However, without the `#include <Arduino.h>`,  I couldn't see the completion result.
(I mimicked cc_args.py's example)

Am I missing something?

**Comment by yuutayamada** [comment]
Sorry, I was missing my code
```cpp
// If I add this, I could see ac-complete-irony-async's result.
#include <Arduino.h>

int main() {
 // ↓ I tried auto-complete here
  d
}
```

**Comment by Sarcasm** [comment]
Like the documentation says (https://github.com/Sarcasm/irony-mode#compilation-database), it should be one flag per line.

**.clang_complete**:

```
-include
/home/uta/share/devkit/arduino-1.6.3/hardware/arduino/avr/cores/arduino/Arduino.h
-I/home/uta/share/devkit/arduino-1.6.3/hardware/arduino/avr/cores/arduino/
-I/home/uta/share/devkit/arduino-1.6.3/hardware/tools/avr/include/
-I/home/uta/share/devkit/arduino-1.6.3/hardware/arduino/avr/libraries/
```

**Comment by Sarcasm** [comment]
It seems to be source of confusion for some people and I can understand, it makes me think whether or not I should split by spaces instead of newline, but then how to handle compile options that requires a space?

For now I think I will continue to answer and maybe try to clear up the documentation or warn the user about something suspicious, not sure what's the best thing to do.

**Comment by yuutayamada** [comment]
Thank you for your rapid reply! It worked.

> For now I think I will continue to answer and maybe try to clear up the documentation or warn the > user about something suspicious, not sure what's the best thing to do.

Sorry, I should have much considered about that part of `one flag per line`.

By the way, I think this package is so great for Arduino users who are
developing on Emacs. I googled one week and there had not been decent
auto-complete package for Emacs. But now I've luckily found irony-mode!
Thank you again for all your effort of irony-mode:)

For your information and someone who wants to use irony-mode on
arduino-mode(I mean .ino extension file) like me, I put my setting:

Emacs setting
```lisp
(add-to-list 'irony-supported-major-modes 'arduino-mode)
;; Treat as arduino-mode as c++
(add-to-list 'irony-lang-compile-option-alist '(arduino-mode . "c++"))

;; arduino-mode turns on if the file has .ino extension
(add-hook 'arduino-mode-hook
  '(lambda ()
     (auto-complete-mode t)
     (irony-mode t)))
```

and

I placed above .clang_complete file, which @Sarcasm wrote, to directory
where I write Arduino's code. (~/Arduino/.clang_complete)

**Comment by Sarcasm** [comment]
For what it's worth, I highly recommend to use company-irony instead of ac-irony, company provides a better API, it supports asynchronous completion without hacks and support for things like annotation is really great for C/C++, as well as brief documentation support. IMHO you should at least try it,that's what I expect to improve on.

**Comment by Sarcasm** [comment]
By the way, I think Arduino is an interesting thing to support, do you think you could put the instruction you put in your last message in the Wiki, in an Arduino page? https://github.com/Sarcasm/irony-mode/wiki/Arduino

Eventually, if you think you will upload your configuration to Github, you could put a link to it  (https://github.com/yuutayamada/emacs.d) at the bottom of the page, so that people can check the current state of your Arduino configuration if it ever change and you don't think about updating the wiki?

Also, IIUC, with Arduino you will always have a set of function available without including the header file Arduino.h automatically? Should irony-mode provide a way to provide such flag automatically (user configurable, not imposed) in Arduino's buffers? So that for the rest of the configuration one only needs to add "third party headers"?

Thanks

**Comment by yuutayamada** [comment]
> IMHO you should at least try it,that's what I expect to improve on.

You are right. I didn't notice that company-mode insert parentheses automatically!

> By the way, I think Arduino is an interesting thing to support, do you think you could put the instruction you put in your last message in the Wiki, in an Arduino page?

Sure! I can gladly write the instruction.

> Also, IIUC, with Arduino will you always have a set of function available without including the header file Arduino.h automatically?

Probably yes. Although I'm still beginner either C/C++ and Arduino, according to http://www.arduino.cc/en/Hacking/BuildProcess (on "Transformations to the main sketch file" section), Arduino IDEs include the Arduino.h file automatically.

> Should irony-mode provide a way to provide such flag automatically (user configurable, not imposed) in Arduino's buffers?

Sure! That will be a help for Arduino users. On above link page's "Build process" section, they explain what they include. My configuration stole from there, so basically it's ok if you provide content of the .clang_complete.

> So that for the rest of the configuration one only needs to add "third party headers"?

Sorry, I'm not clear about this. I mean I don't try this feature seriously yet. But when I tried my Arduino IDE's library manager, the manager installed a library to ~/Arduino/libraries/THE_LIBRARY_NAME/. So, you should add this directory as include directory. (probably)

**Comment by yuutayamada** [comment]
So,,, like this?

```lisp
(defvar irony-arduino-home (or (getenv "ARDUINO_HOME") "")
  "Arduino IDE's path (i.e., ~/arduino-1.6.3).")
(defvar irony-arduino-header-path
  (format "%s/hardware/arduino/avr/cores/arduino/Arduino.h" irony-arduino-home)
  "Path of Arduino.h, which the Arduino IDE includes automatically.")
(defvar irony-arduino-include-base-directory
  (cl-loop with dirs = '("/hardware/arduino/avr/cores/arduino/"
                         "/hardware/tools/avr/include/" "/hardware/arduino/avr/libraries/")
           for include-dir in dirs
           collect (format "%s%s" irony-arduino-home include-dir) into include-dirs
           ;; Add Arduino's third party library directory
           finally return (append '("~/Arduino/libraries") include-dirs)))
```

Feel free to change or add anything.

**Comment by Sarcasm** [comment]
> Probably yes. Although I'm still beginner either C/C++ and Arduino, according to http://www.arduino.cc/en/Hacking/BuildProcess (on "Transformations to the main sketch file" section), Arduino IDEs include the Arduino.h file automatically.

Thanks for the links.



> So,,, like this?
> ...

Hum, no I wasn't thinking about doing something Arduino specific just now. I was just wondering if I could do something better than `irony-additional-clang-options` if that is needed. That was just a thought, but I don't want to include Arduino's specific just now.

We will see what is useful, what ends up in the Wiki's page first, and then maybe someday provide some Arduino's specific support in irony-mode.

**Comment by yuutayamada** [comment]
> Hum, no I wasn't thinking about doing something Arduino specific just now. I was just wondering if I could do something better than irony-additional-clang-options if that is needed. That was just a thought, but I don't want to include Arduino's specific just now.

I see.

> We will see what is useful, what ends up in the Wiki's page first, and then maybe someday provide some Arduino's specific support in irony-mode. Right now I cannot say what is the good way to include Arduino.

Hi, I wrote the Arduino wiki page.
But I also wrote an emacs lisp package for the configuration because I
wouldn't mess up your irony-mode's issue page and I have Arduino's
environment. (https://github.com/yuutayamada/company-arduino)
I think it's better to extract about the include path's information
and it will be less configuration for users.
Probably Arduino's experts notice me if they have complain:)

Would you mind? 
I'll rewrite the wiki page later if you don't mind.

**Comment by Sarcasm** [comment]
A package is great! You should add it to the wiki page. :)

Just a thought about the name company-arduino, maybe one day you will realize that you want more than just completion, and maybe you will want to have syntax checking (with flycheck for example, or flymake, ...), code indexing (with ???), ...when this happens the name company-arduino may be misleading. Maybe that is not an issue since you can create a new package instead of adding this to company-arduino (that's what I do with irony, company-irony, company-flycheck, ...).
