### ISSUE TITLE
Possible new functionality

### ISSUE THREAD

**Issue by hotpxl** [Sarcasm/irony-mode#223]
Since Irony is built upon clang, I wonder if more functionalities are going to be implemented. I get the idea of less code keeps the whole program smooth and steady. So I'm not asking for new features. I just want to know what you are thinking of them, whether they are better implemented (or is already implemented) elsewhere.

* Jump to declaration. I saw this once in an earlier issue. You said it's better to use another indexed tool like rtags. I agree.
* Get type of symbol. I think this one could probably be a really cool feature. I think invoking clang would take only a couple lines of code? I am not sure if it's already implemented.

**Comment by Sarcasm** [comment]
Yes, I have plenty of feature ideas, irony-server purpose is to provide useful "editing" operations, code indexing doesn't fit into this and is something a dedicated tool (or set of tools) should provide. So I'm absolutely not against new features, but I want features that somewhat straightforward, working usually on a file and not on a whole project.

> Jump to declaration. I saw this once in an earlier issue. You said it's better to use another indexed tool like rtags. I agree.

I would say that "jump to declaration" fits a little bit in what I'm okay to provide but "find reference" doesn't. Jumping to a declaration is useful to see the whole comment, the parameters, some comments/annotations on the code, etc. It will be useful to add but at the same time weird because doing the counterpart, "jump to definition", isn't easy implemented. Before jumping to a declaration I would like to have a mechanism to jump from "header file" -> "source file" and vice versa, with `ff-find-other-file`. This doesn't even need work on irony-server.

> Get type of symbol. I think this one could probably be a really cool feature. I think invoking clang would take only a couple lines of code? I am not sure if it's already implemented.

Yeah, this one is spot-on, I would like to have it! Using `auto`, it will be nice to display the inferred type. :)
This one I think would be nice to implement on the server-side only first, to discuss it. Then think about the elisp bits.

FYI, I'm working locally on a better "framework" to communicate with irony-server, in order to make it easier to write new commands because I have found it difficult to add new commands. It seems to work so far but since this touches the core logic I have to come back to feature parity before I can publish it.

As always, contributions are most welcomed. :)
I may be reluctant to big changes because there is a lot of small tasks that would be useful already (just elisp + compile options related like `ff-find-other-file`) and because I'm rewriting the core and I don't want this to be an endless task where I have to catch up with all the new commands.

**Comment by hotpxl** [comment]
> Before jumping to a declaration I would like to have a mechanism to jump from "header file" -> "source file" and vice versa, with ff-find-other-file. This doesn't even need work on irony-server.

This would be really hard to implement. Because it's not always a header paired with a source file. But in `company-irony-c-headers` I can get the location of the header file. So it is possible to point to a header file and say jump. But otherwise, I think jumping directly to the corresponding header file might be hard.

One way I can think of, is to find a file of the same name only with `.cpp` replaced by `.h`. This would satisfy 99% of the situations. It should find this file in the header search path, to deal with cases when the header file and the source file are not in the same directory.

Clang does provide a "jump to definition" functionality if my memory serves me right. But it's not that accurate when dealing with templates.

> Yeah, this one is spot-on, I would like to have it! Using auto, it will be nice to display the inferred type. :)
This one I think would be nice to implement on the server-side only first, to discuss it. Then think about the elisp bits.

For getting types, I think Clang already does a pretty good job. There are situations when it can't get the type. For example, when you are declaring a variable `auto` and on the same declaration you invoke the command, it's just gonna return `auto`. But it works when you are trying to use the variable. We could wait for the new framework and see how it could be implemented into the server. I'd love to see what I can do about this part.

Thanks for your response. I just want to check in and see if new stuff is going to be implemented. It's always better to have more functionalities built in one tool. But not at the cost of losing stability and code readability. Thank you for providing such a great tool.

**Comment by Sarcasm** [comment]
> This would be really hard to implement. Because it's not always a header paired with a source file. But in company-irony-c-headers I can get the location of the header file. So it is possible to point to a header file and say jump. But otherwise, I think jumping directly to the corresponding header file might be hard.

It is acceptable to have no matching file but it is useful to find it when one exists. With `ff-find-other-file` I think the only thing needed is to provide `cc-search-directories`.

> We could wait for the new framework and see how it could be implemented into the server. I'd love to see what I can do about this part.

FYI, I suggested to do it server side because nothing much changes on the server side. And like you said, if `auto` is causing issues it would be good to know it.
