### ISSUE TITLE
Class private methods autocomplete

### ISSUE THREAD

**Issue by impowski** [Sarcasm/irony-mode#292]
When I'm implementing a class in .cpp file and it autocomplete public methods perfectly but I can't see any of private methods. But I still don't understand is that me or it's just how it works? How I supposed to use it with 20 or 30 private methods in class when I cant remember all names of functions to implement them? For example:

``` C++
class A {
public:
    void show();
private:
    void dah();
};
```

And when I do:

``` C++
void A::
```

its showing only `show()` and some default stuff like constructor and etc. but no private function. Is there any workaround?

---

/edit from @Sarcasm: change private method `do()` -> `dah()` the former conflicted with the `do` keyword./

**Comment by 3246251196** [comment]
I have noticed this. I don't think clang can do this without first knowing whether it can display private methods. When you starting implementing the method 

A::

you are still not really in the scope of the class so clang does the right thing by only showing public methods.

??

**Comment by jkaye2012** [comment]
I see this as well, would be interested to know what's going on here.

**Comment by Sarcasm** [comment]
This is the second issue on this subject, the reason comes from this piece of code:

* https://github.com/Sarcasm/irony-mode/blob/3d64dec24b01bc582801db537ed12a5812f4f0ee/server/src/Irony.cpp#L261-L264

Clang categorize this code as being inaccessible.


I tested with c-index-test:

```
$ ./bin/c-index-test -code-completion-at=/tmp/foo.cpp:8:9 /tmp/foo.cpp
ClassDecl:{TypedText A} (35)
CXXMethod:{ResultType void}{TypedText dah}{LeftParen (}{RightParen )} (35) (inaccessible)
CXXMethod:{ResultType A &}{TypedText operator=}{LeftParen (}{Placeholder const A &}{RightParen )} (35)
CXXMethod:{ResultType void}{TypedText show}{LeftParen (}{RightParen )} (35)
CXXDestructor:{ResultType void}{TypedText ~A}{LeftParen (}{RightParen )} (35)
```

This bug looks similar to https://github.com/Sarcasm/company-irony/issues/22
Best would be to fix libclang.
We could imagine irony-server offering a way to display inaccessible members as a "second stage"/alternative completion step.
