### ISSUE TITLE
How to get completion when making a header only library?

### ISSUE THREAD

**Issue by AriaFallah** [Sarcasm/irony-mode#354]
Do you know of any reliable way? I know headers aren't picked up by the `compile_commands.json` so I'm trying to figure out how to use `irony-mode`, and I'm coming up blank.

**Comment by Sarcasm** [comment]
2 main situations in my opinion:

1. the library is header only and has little dependency. Just make a .clang_complete file with one flag per line at the root of the project
2. the flags can be complex, and the code is unit tested. Pick up the flags from the unit tests. For this, I have started to work on https://github.com/Sarcasm/compdb and its `headerdb` subcommand attempts to do this.

**Comment by AriaFallah** [comment]
Hopefully I'm not asking for too much hand holding here, but I'm very new to writing C++ and C++ in emacs.

Here's the project I recently started https://github.com/AriaFallah/csv-parser, and it does have unit tests here https://github.com/AriaFallah/csv-parser/blob/master/test/test.cpp. Of the methods, 1 and 2, which should I use?

Also regarding https://github.com/Sarcasm/compdb, I only see how to install it using `pip`, but nothing regarding how to actually use it. Could you provide some further guidance there?

**Comment by Sarcasm** [comment]
Looking at your project, it looks like your header is self-contained, and only depends on the STL.
So the compile options should not matter, you don't need a JSON compilation database nor a .clang_complete.

The test file requires Catch, so you may have to create a `.clang_complete` with a compile option that point to the directory where Catch is present. It seems you include ./catch.hpp, so I don't think you need this.

Regarding compdb, it's not yet documented but it's supposed to be self-documented.
You install, you type `compdb` it tells you what you can do. But honestly, I don't recommend you to look at it just now, it's not more documented because it's not yet ready for prime time (when it will be is a mystery to me too).

**Comment by AriaFallah** [comment]
> Looking at your project, it looks like your header is self-contained, and only depends on the STL.
So the compile options should not matter, you don't need a JSON compilation database nor a .clang_complete.

This is basically exactly why I made the issue / what I'm confused about. I know the project isn't necessarily large so autocomplete isn't a big deal, but I would still like it to work for the variables that I declare in the header.

So for example `std::vector` will give me autocompletion options, but if I want to use the internal `enum class State` I get no autocompletion options, and typing `State::SOME_STATE` over and over isn't so fantastic. Is there any way to get completion for just the single file? Even if it's not `company-irony`?

**Comment by Sarcasm** [comment]
Hum, my bad, you need a `.clang_complete` for C++11.

That is:

    echo '-std=c++11' > .clang_complete

For me this was enough to have completion in parser.hpp, I could complete `State::|` in method bodies.

**Comment by AriaFallah** [comment]
Works perfectly :)

**Comment by Sarcasm** [comment]
Great! :+1:
