### ISSUE TITLE
Problem to build version 1.0 in MSVC 2017

### ISSUE THREAD

**Issue by mambolevis** [Sarcasm/irony-mode#387]
Hi,
the following messages appeared when I tried to build Irony version 1.0. In general, I did not have any problem to build irony in visual studio until version 1.0. 
I am using CMake 3.8.1 in order to be able to target MSVC 2017. 

Thank you for your help.

```
1>------ Build started: Project: ZERO_CHECK, Configuration: Release x64 ------
1>Checking Build System
1>CMake does not need to re-run because C:/home_levis/.emacs.d/user/site-lisp/irony-1.0/build_msvc2017/CMakeFiles/generate.stamp is up-to-date.
1>CMake does not need to re-run because C:/home_levis/.emacs.d/user/site-lisp/irony-1.0/build_msvc2017/src/CMakeFiles/generate.stamp is up-to-date.
1>CMake does not need to re-run because C:/home_levis/.emacs.d/user/site-lisp/irony-1.0/build_msvc2017/docs/CMakeFiles/generate.stamp is up-to-date.
1>CMake does not need to re-run because C:/home_levis/.emacs.d/user/site-lisp/irony-1.0/build_msvc2017/test/CMakeFiles/generate.stamp is up-to-date.
1>CMake does not need to re-run because C:/home_levis/.emacs.d/user/site-lisp/irony-1.0/build_msvc2017/test/elisp/CMakeFiles/generate.stamp is up-to-date.
2>------ Build started: Project: irony-server, Configuration: Release x64 ------
3>------ Skipped Build: Project: Continuous, Configuration: Release x64 ------
3>Project not selected to build for this solution configuration 
4>------ Skipped Build: Project: Experimental, Configuration: Release x64 ------
4>Project not selected to build for this solution configuration 
5>------ Skipped Build: Project: Nightly, Configuration: Release x64 ------
5>Project not selected to build for this solution configuration 
6>------ Skipped Build: Project: NightlyMemoryCheck, Configuration: Release x64 ------
6>Project not selected to build for this solution configuration 
7>------ Skipped Build: Project: RUN_TESTS, Configuration: Release x64 ------
7>Project not selected to build for this solution configuration 
8>------ Skipped Build: Project: check, Configuration: Release x64 ------
8>Project not selected to build for this solution configuration 
9>------ Skipped Build: Project: doxygen, Configuration: Release x64 ------
9>Project not selected to build for this solution configuration 
2>Building Custom Rule C:/home_levis/.emacs.d/user/site-lisp/irony-1.0/server/src/CMakeLists.txt
2>CMake does not need to re-run because C:/home_levis/.emacs.d/user/site-lisp/irony-1.0/build_msvc2017/src/CMakeFiles/generate.stamp is up-to-date.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.10.25017\bin\HostX86\x64\CL.exe /c /I"C:\Program Files\LLVM-3.9.1\include" /I"C:\home_levis\.emacs.d\user\site-lisp\irony-1.0\server\src" /nologo /W3 /WX- /diagnostics:classic /O2 /Ob2 /D WIN32 /D _WINDOWS /D _HAS_EXCEPTIONS=0 /D NDEBUG /D "CLANG_BUILTIN_HEADERS_DIR=\"C:/Program Files/LLVM-3.9.1/lib/clang/3.9.1/include\"" /D "CMAKE_INTDIR=\"Release\"" /D _MBCS /Gm- /EHsc /MD /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"irony-server.dir\Release\\" /Fd"irony-server.dir\Release\vc141.pdb" /Gd /TP /errorReport:prompt   /EHs-c- "C:\home_levis\.emacs.d\user\site-lisp\irony-1.0\server\src\support\CommandLineParser.cpp" "C:\home_levis\.emacs.d\user\site-lisp\irony-1.0\server\src\support\TemporaryFile.cpp" "C:\home_levis\.emacs.d\user\site-lisp\irony-1.0\server\src\Command.cpp" "C:\home_levis\.emacs.d\user\site-lisp\irony-1.0\server\src\Irony.cpp" "C:\home_levis\.emacs.d\user\site-lisp\irony-1.0\server\src\TUManager.cpp"
2>cl : Command line warning D9025: overriding '/EHs' with '/EHs-'
2>cl : Command line warning D9025: overriding '/EHc' with '/EHc-'
2>CommandLineParser.cpp
2>TemporaryFile.cpp
2>C:\home_levis\.emacs.d\user\site-lisp\irony-1.0\server\src\support\TemporaryFile.cpp(22): warning C4996: 'getenv': This function or variable may be unsafe. Consider using _dupenv_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
2>C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\ucrt\stdlib.h(1188): note: see declaration of 'getenv'
2>Command.cpp
2>C:\home_levis\.emacs.d\user\site-lisp\irony-1.0\server\src\Command.cpp(200): warning C4244: 'initializing': conversion from '__int64' to 'int', possible loss of data
2>C:\home_levis\.emacs.d\user\site-lisp\irony-1.0\server\src\Command.cpp(200): warning C4244: 'initializing': conversion from '__int64' to 'const int', possible loss of data
2>Irony.cpp
2>C:\home_levis\.emacs.d\user\site-lisp\irony-1.0\server\src\Irony.cpp(100): error C2666: 'std::fpos<_Mbstatet>::operator ==': 3 overloads have similar conversions
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.10.25017\include\iosfwd(103): note: could be 'bool std::fpos<_Mbstatet>::operator ==(std::streamoff) const'
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.10.25017\include\iosfwd(98): note: or       'bool std::fpos<_Mbstatet>::operator ==(const std::fpos<_Mbstatet> &) const'
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.10.25017\include\exception(336): note: or       'bool std::operator ==(const std::exception_ptr &,const std::exception_ptr &) throw()' [found using argument-dependent lookup]
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.10.25017\include\exception(341): note: or       'bool std::operator ==(std::nullptr_t,const std::exception_ptr &) throw()' [found using argument-dependent lookup]
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.10.25017\include\exception(346): note: or       'bool std::operator ==(const std::exception_ptr &,std::nullptr_t) throw()' [found using argument-dependent lookup]
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.10.25017\include\system_error(362): note: or       'bool std::operator ==(const std::error_code &,const std::error_code &) throw()' [found using argument-dependent lookup]
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.10.25017\include\system_error(370): note: or       'bool std::operator ==(const std::error_code &,const std::error_condition &) throw()' [found using argument-dependent lookup]
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.10.25017\include\system_error(378): note: or       'bool std::operator ==(const std::error_condition &,const std::error_code &) throw()' [found using argument-dependent lookup]
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.10.25017\include\system_error(386): note: or       'bool std::operator ==(const std::error_condition &,const std::error_condition &) throw()' [found using argument-dependent lookup]
2>C:\home_levis\.emacs.d\user\site-lisp\irony-1.0\server\src\Irony.cpp(100): note: or       'built-in C++ operator==(std::streamoff, int)'
2>C:\home_levis\.emacs.d\user\site-lisp\irony-1.0\server\src\Irony.cpp(100): note: while trying to match the argument list '(std::fpos<_Mbstatet>, int)'
2>C:\home_levis\.emacs.d\user\site-lisp\irony-1.0\server\src\Irony.cpp(271): warning C4267: 'argument': conversion from 'size_t' to 'unsigned int', possible loss of data
2>C:\home_levis\.emacs.d\user\site-lisp\irony-1.0\server\src\Irony.cpp(419): warning C4267: 'argument': conversion from 'size_t' to 'unsigned int', possible loss of data
2>C:\home_levis\.emacs.d\user\site-lisp\irony-1.0\server\src\Irony.cpp(421): warning C4267: 'argument': conversion from 'size_t' to 'unsigned int', possible loss of data
2>C:\home_levis\.emacs.d\user\site-lisp\irony-1.0\server\src\Irony.cpp(432): warning C4267: '=': conversion from 'size_t' to 'unsigned int', possible loss of data
2>C:\home_levis\.emacs.d\user\site-lisp\irony-1.0\server\src\Irony.cpp(468): warning C4267: '=': conversion from 'size_t' to 'unsigned long', possible loss of data
2>TUManager.cpp
2>C:\home_levis\.emacs.d\user\site-lisp\irony-1.0\server\src\TUManager.cpp(115): warning C4267: 'argument': conversion from 'size_t' to 'unsigned int', possible loss of data
2>C:\home_levis\.emacs.d\user\site-lisp\irony-1.0\server\src\TUManager.cpp(139): warning C4267: 'argument': conversion from 'size_t' to 'unsigned int', possible loss of data
2>Generating Code...
2>Done building project "irony-server.vcxproj" -- FAILED.
10>------ Build started: Project: ALL_BUILD, Configuration: Release x64 ------
10>Building Custom Rule C:/home_levis/.emacs.d/user/site-lisp/irony-1.0/server/CMakeLists.txt
10>CMake does not need to re-run because C:/home_levis/.emacs.d/user/site-lisp/irony-1.0/build_msvc2017/CMakeFiles/generate.stamp is up-to-date.
11>------ Skipped Build: Project: INSTALL, Configuration: Release x64 ------
11>Project not selected to build for this solution configuration 
========== Build: 2 succeeded, 1 failed, 0 up-to-date, 8 skipped ==========
```

**Comment by Sarcasm** [comment]
You can try to apply the following patch to Irony.cpp(100):

```diff
  auto nbytes = ifs.tellg();

-  if (nbytes == -1) {
+  if (nbytes == std::ifstream::pos_type(-1)) {
    return false;
  }
```

Let me know if that works.

**Comment by mambolevis** [comment]
It works perfectly. Thanks.

Question: 
I usually build two projects, for example:` irony-1.0 and irony-1.0-patch`
The second one, `irony-1.0-patch`, has the following modification:
```
/*   if (CINDEX_VERSION < 6) {
    parseTUOptions_ &= ~CXTranslationUnit_PrecompiledPreamble;
  } */

  // windows required patch
  if (true) {
    parseTUOptions_ &= ~CXTranslationUnit_PrecompiledPreamble;
  }
```
As you know, the patch is required to avoid the following error when adding the `first include` to a c++ file. 
![image](https://cloud.githubusercontent.com/assets/13024208/26219107/d665e9d4-3c0d-11e7-8bc3-e9df23ad584d.png)

The point is that the patch version affects the performance of the completion drastically.  So, now my question:
`- Is it possible to create a elisp function that stops irony-server when editing the first include and run again for the rest of the c++ file? ` I preffer no completion in the `first include line` but performance in the rest of the c++ file, what do you think about it?

**Comment by Sarcasm** [comment]
I don't remember the ins and outs of this bug.
What do you mean by "the first include"?
If it's all there is to it, I would be fine merging a workaround, for example, maybe expose these flags to elisp, so that a hook function in elisp can disable it at first and then enable it.

@3246251196 do you have the same patch?

**Comment by mambolevis** [comment]
The first include means the first include directive in a  **`.cpp`** file. I made several tests, and the problem only occurred in .cpp file.

```
// *.cpp file description
#include <vector>       //this is the first include directive.
#include <string>
```

Yes, a workaround is a very good idea. Great, I am ready to test your proposal!

**Comment by Sarcasm** [comment]
So the code does not work in this region of the code:

```
// *.cpp file description
#include <vector>       //this is the first include directive.
```

But works starting from this region, before or after this include:

```cpp
#include <string>
```

Is that right?

Honestly, it's not too challenging but it's very specific, probably not the "right" fix, I'm not sure I want to spend my free time on this.
However, I'm usually happy to review the code and propose ideas.

**Comment by mambolevis** [comment]
Yes, it works after the first include. It only fails in the first include directive of the *.cpp

You are right, it is very specific and only for windows users, but a workaround in this old bug will be very welcome because it implies performance.

**Comment by 3246251196** [comment]
@Sarcasm 
I was meaning to post about that compilation error. I crudely just c-style cast to (int), but the more elegant fix is yours.

Anyway, I generally use the patched version (of which I think we are talking about: NOT USING PreCompiledPreambles) as I often used to run into the same issue.

To make things clear, at work I have performance issue with code completion too since we have an old code base with many header files that make for a huge translation unit. On top of that, we use BOOST which is the main issue.

To get around the boost performance I actually trick clang compile flags for my .clang_complete. I copy the entire boost header file library and simply truncate every file and point my .clang_complete to this fake library. This way, when clang is parsing it cannot complain about there being no such header file and I get quicker completion. Why do I do this? Because when I want to understand any APIs or structure offered by boost I generally consult the BOOST pages anyway. All the templated completions make it hard to even read the completion suggestions in company-mode. So now, I get quicker completion using the core code-base (at work) and other external libs (which are quick because they do not include lots and lots of templates).

Therefore, due to not having proper boost header files I will get issues when using PreCompiledPre-Amble etc.

Something else comes to my attention. You are using an older version of clang. Perhaps upgrading might help ONLY BECAUSE they might have created a release where assertions are not dealt with in RElease mode. Looking at the llvm/clang pages, you can compile the source with 
```
DLLVM_ENABLE_ASSERTIONS=Off
```
http://llvm.org/docs/GettingStarted.html

They have not documented that part too well (if you search for ENABLE_ASSERTIONS in the page link) They say =On and then in brackets (default Yes otherwise No). But, you get the idea. You should be able to disable assertions, or hack the source to remove it  - but this is obviously not the best way to do it. I do wonder, though, why assertions are being raised if you have 3.7 release. 

Anyway, I hope any of this helps.

**Comment by Sarcasm** [comment]
Just a thought,
did anyone of you tried to change the compile options so that they use the `-include` option?

For example a `.clang_complete` starting with:
```
-include
foo.h
<other options below>
```

**Comment by mambolevis** [comment]
@3246251196 
Thank you for your comments. I build irony 1.0 with LLVM-4.0.0. The message with the assertion failure that you mention was solved. 
Now, the following message is shown in the minibuffer when I am editing the first include directive.

`Error from syntax checker irony: Irony-Mode server error: parse-error, "failed to parse file", "d:/Developer/03_C++/02_Collection/02_Advanced/01_Unit_Test/1_UnitTest++/modules/mod2_Money/src/main.cpp"`

**Comment by mambolevis** [comment]
```
Just a thought,
did anyone of you tried to change the compile options so that they use the -include option?
```

@Sarcasm 
My .clang_complete looks like this:
```
-target
i686-pc-windows-msvc
-fms-extensions
-fms-compatibility
-fms-compatibility-version=19
-fdelayed-template-parsing
-I./include
-I../common
-I../common/UnitTest++/src
-I../common/UnitTest++/src/tests
```
What should I modify for testing your suggested thought?

**Comment by 3246251196** [comment]
@mambolevis 
Since Windows installs libraries to ... god-knows where, unlike /usr/include etc, I would just to make sure that you are including the externals libs into your project.

For example I have to include 
/IC:\Path\To\Boost
etc.

Just checking.

I think @Sarcasm would like you to try 

```
-target
i686-pc-windows-msvc
-fms-extensions
-fms-compatibility
-fms-compatibility-version=19
-fdelayed-template-parsing
-include
./include
-include
../common
-include
../common/UnitTest++/src
ETC
```

**Comment by 3246251196** [comment]
It might be worth removing all MS-type-stuff from your .clang_complete and just see what happens with just including includes and any definitions you use. Just a thought.

**Comment by Sarcasm** [comment]
What I meant is, if you have the following `.clang_complete`:

```
-target
i686-pc-windows-msvc
-fms-extensions
-fms-compatibility
-fms-compatibility-version=19
-fdelayed-template-parsing
-I./include
-I../common
-I../common/UnitTest++/src
-I../common/UnitTest++/src/tests
```

Modify it like this way:
First, create foo.h, in the same directory as `.clang_complete`, with the following content:

**foo.h**:
```
#include <vector>'
```

Then, complement `.clang_complete` so that it ends with these 2 new lines:

```
-target
i686-pc-windows-msvc
-fms-extensions
-fms-compatibility
-fms-compatibility-version=19
-fdelayed-template-parsing
-I./include
-I../common
-I../common/UnitTest++/src
-I../common/UnitTest++/src/tests
-include
foo.h
```

The `-include` option, includes a file before processing the file, this means clang will have parsed some headers even before the first line of your file.

**Comment by mambolevis** [comment]
@Sarcasm 
I made your suggested changes in .clang_complete and re-stated emacs again. This solves the problem, and now there is no message when editing the first include directive in a .ccp file. 
What is you final recommendation, in case of one, or have you visualized a solution?

@3246251196 
It is just for answer your questions.
1) Yes, I am including non project headers like boost etc. 
2) If I remove all MS-type-stuff from your .clang_complete Irony shows the following error:  Error from `syntax checker irony: Irony-Mode server error: parse-error, "failed to parse file", "d:/Developer/03_C++/02_Collection/02_Advanced/01_Unit_Test/1_UnitTest++/modules/mod2_Money/src/main.cpp"`

**Comment by Sarcasm** [comment]
So, if I understand correctly you could:

Create a **clang-windows-include-fix.h** in your .emacs.d/ directory with the following content:

```cpp
/* Workaround irony/libclang bug on MSVC:
   https://github.com/Sarcasm/irony-mode/issues/387#issuecomment-302775453 */
#include <string.h>
```

This file should be C-compatible, in case you happen to also work with C.

Configure `irony-additional-clang-options` to add the `-include` option automatically.
In your emacs config:

```el
;; workaround irony/libclang bug on MSVC
;; see https://github.com/Sarcasm/irony-mode/issues/387#issuecomment-302775453
(setq irony-additional-clang-options
      (list "-include"
            (locate-user-emacs-file "clang-windows-include-fix.h"))
```

Remove your modifications to TUManager.cpp if that's good now.

That's not a proper "solution", but it's a workaround.
A real solution would be that someone using Windows investigate the root cause and fix it.

If this workaround is good enough for you two, it would be nice to document this in the Wiki page:

- https://github.com/Sarcasm/irony-mode/wiki/Setting-up-irony-mode-on-Windows-using-MSVC

**Comment by mambolevis** [comment]
@Sarcasm 
Thank you!
I think that the workaround is a very small price to pay in order to gain completion performance. 

Another important conclusion from this issue, is that using a release version of libclang users have the possibility to live with the problem; they only will be informed in the mini buffer but irony won't be blocked. In the case of using a debug version of the libclang, a message form will be shown impeding a fluent user programming. 

@3246251196 
Thank you for your help, I was accidentally using a debug version of libclang but your comments helped me to find the right path.

Grüße

**Comment by mambolevis** [comment]
Hi,

`If this workaround is good enough for you two, it would be nice to document this in the Wiki page:`

Before updating the wiki, I wanted to test the workaround this weekend. After making some test I realized that the workaround is not necessary.

Solution to the problem:

After making several test, I realized that the problem was in the official Pre-Built Binaries [http://releases.llvm.org/download.html#4.0.0](url) that I used to install `libclang.dll`. 

I follow the recommendations from @yaruopooner (`https://github.com/yaruopooner/ac-clang`) where he build its own `libclang.dll`. So, I downloaded the binary  `Clang 4.0.0 support 64/32bit binaries` from `https://github.com/yaruopooner/ac-clang/releases` and tested it in several projects.

**Summary of using ` libclang.dll` from @yaruopooner** :
- It solves the problem and it is not necessary  to use the patch in irony's TUManager.cpp file anymore
- The completion performance is excellent
- It will be helpful if user @3246251196 test also the solution
- I only have reduction in completion Performance when I use libraries such `Boost` and `eigen3` 

@3246251196 
Could you attach an example with your solution to improve completion performance when using `Boost` and `eigen3` libraries?

Thanks

**Comment by 3246251196** [comment]
@mambolevis 

I would like to try this first. In order to try it I am trying to do the following:

- Download the release from the link you have attached.
- install-irony-server pointing to the new libclang library.. oh, wait, there is no .lib file, just a .dll file - therefore, I cannot build irony-server with the libclang provided.

I assume you are not using clang-server.exe at all, and you are just linking with the modified libclang library?

When I look at the main page of the link there seems to be no explanation of what the guy has actually done to improve performance. The only thing I can go on is:

- Download the SOURCE code instead,
- Open the invalidate-mmap.patch file in the folder "patch"

There I see that he is basically early returning from some function (whose signature I cannot see and I cannot be bothered to look at the source tree I currently have of clang). It would be nice to get confirmation that it is *this* patch that is the all-encompassing change that has been made to improve the performance of libclang - and, therefore, Irony.

In the meantime, I will apply such a patch myself to MemoryBuffer.cpp and see if I notice any improvement on the premise that my assumption (that the improvement is merely the change in MemoryBuffer.cpp) is correct. 

Thank you @mambolevis , when you reply we can work further on this.

**Comment by mambolevis** [comment]
@Sarcasm 

`I assume you are not using clang-server.exe at all, and you are just linking irony-server with the modified libclang library?`

Yes, your assuption is correct, I am not using clang-server.exe. To reproduce my tests, just use the **libclang.dll** from https://github.com/yaruopooner/ac-clang and be sure that irony-server.exe used it.

The key point is to build  libclang.dll using his patch. The explanation is given here https://github.com/yaruopooner/ac-clang/blob/master/clang-server/readme.md#self-build . He also provides a script to build and patch LLVM https://github.com/yaruopooner/llvm-build-shells

Please let me know if you need something else.

Question
-Do you know the trick user @3246251196 made to solve the completion performance of irony when using Boost header files? Can you give an example?

**Comment by 3246251196** [comment]
@mambolevis 
Mambolevis, for irrelevant reasons I cannot use the scripts he supplies. I would just like to confirm that the two patches to apply are the following:

https://raw.githubusercontent.com/yaruopooner/llvm-build-shells/master/patch/bugfix000.patch
https://github.com/yaruopooner/ac-clang/blob/master/clang-server/patch/invalidate-mmap.patch

---

I will talk about the boost examples afterwards.

**Comment by 3246251196** [comment]
@mambolevis 

So I have just been testing this out with quick completions by using my boost "hack".

Assume that boost is fully installed in a location c:/myBoostFiles/boost/

{code}
cp -rf c:/myBoostFiles c:/FAKE_myBoostFiles
cd c:/myBoostFiles c:/FAKE_myBoostFiles
for boostFile in $(find . -name "*.hpp") ; do truncate --size 0 $boostFile ; done
{code}

Then, point your clang_complete to FAKE_myBoostFiles rather than myBoostFiles.

Due to the occassional assertion failure I to and fro about this. For example, I am currently using proper include flags just to see how things go. Remember that the first parse takes a long time, but if we have pre-compiled headers and *reparse then the optimizations make completions instant.

Anyway, I just wanted to show you what can be done. But it is not an elegant solution at all!

**Comment by mambolevis** [comment]
@3246251196  
Trank you for your answer. 
I follow your suggestions I made some preliminary tests:
1. In an small project that uses Boost alone irony completion performance is excellent and the same with and without the "FAKE" boost includes.

2. In a big project the is where the performance is affected. It doesn't mater if I use either standard boost includes or "FAKE" trick files.

So, I will continue the tests and if necessary I will open a new issue.

**Comment by 3246251196** [comment]
@mambolevis

Hello, would you be be able to do me a great favour and just confirm that the two patches I think are the fixes are correct and that I am not missing something.

cheers.

**Comment by mambolevis** [comment]
@3246251196 
Hi, yes the two patches are the fixes. 
Try first to use irony-server.exe with the libclang.dll provided by ac-clang, or do you have already tried?

**Comment by 3246251196** [comment]
@mambolevis 
Hi, I have tried, but I get:
{code}
C:\the\location\libclang.dll : fatal error LNK1107: invalid or corrupt file: cannot read at 0x368 [c:\some\location\irony-server.vcxproj]
{code}

I have checked and believe that the libclang.dll is a 64 bit object, just like my irony-server.exe - not sure what is wrong. For now I have manually applied the two patches and build my own version.

**Comment by mambolevis** [comment]
@3246251196 

`I have checked and believe that the libclang.dll is a 64 bit object, just like my irony-server.exe - not sure what is wrong. For now I have manually applied the two patches and build my own version.`

Hi, do you have something new? please let me know the result of your tests.

**Comment by 3246251196** [comment]
@mambolevis 
Hello, I just manually apply the patches to a trunk llvm/clang and then use libclang from the build, so this is no longer an issue.

If you mean whether I have something new with regards to the version using the patches: I personally do not find any great increase in performance. One of the problems is that we use precompiled headers ourselves. This means including stdafx.h which is used in all compilation units which forces the parsing of a lot of boost templates. 

Cheers.

**Comment by mambolevis** [comment]
@3246251196 
Yes, I think we can close this issue. 

The most important improvement, in my case, is that I don't need to use the patch in irony anymore, the one in the TUManager.cpp file, and it implies automatically: completion performance and stability. I also don't need to use:
```
-target
i686-pc-windows-msvc
-fms-extensions
-fms-compatibility
-fms-compatibility-version=19
-fdelayed-template-parsing
```

Regarding the performance of irony when using Boost library, yes it is another issue. I will make more tests before opening a new issue around this topic.

Grüße,

**Comment by 3246251196** [comment]
@mambolevis
@Sarcasm

I am noticing that the latest version of Clang is as quick as ever even with our big code base at work. It is good. 

Also, I will make a pull request soon I think to remove the hack to allow people to see protected members in parent classes: they have fixed that issue recently.

I no longer need to apply the patch we talked about in this thread since clang seems to be running very fast.

Cheers all, hope all is well.

**Comment by Sarcasm** [comment]
Ah, that is good to hear, the cleaning up PR would be most appreciated! :)

**Comment by mambolevis** [comment]
Yes, I agree, we can close this issue. In my case everything is working fine.  Thank you guys for the excellent job.
Saludos
